<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nitsan_sharethis"
 *
 * Auto generated by Extension Builder 2016-09-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Nitsan Sharethis',
	'description' => 'ShareThis provides free sharing buttons and tools to drive traffic and increase engagement on your site..',
	'category' => 'plugin',
	'author' => 'Sanjay Chuahan',
	'author_email' => 'sanjay@nitsan.in',
	'author_company' => 'nitsan.in',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.7-7.99.99',
			'extbase' => '6.2.0-7.99.99',
			'fluid' => '6.2.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);